<?php include('../templates/includes/html-head.phtml'); ?>

<?php if (!empty($data['msg'])) { ?>
	<p class="message"><?php echo $data['msg']; ?></p>
<?php } ?>

<dl class="device-detail">
	<di class="device-detail--mac__header">Mac</di>
	<dd class="device-detail--mac"><?php echo $data['device']->getMac() ?></dd>
	<di class="device-detail--type__header">Type</di>
	<dd class="device-detail--type"><?php echo $data['device']->getType() ?></dd>
	<di class="device-detail--info__header">Info</di>
	<dd class="device-detail--info"><p><?php echo $data['device']->getInfo() ?></p></dd>
</dl>

<?php
	foreach ($data['device']->getVersions() as $deviceVersion) {
?>
<dl class="detail detail__device-version">
    <di class="detail__device-version--version__header">Version</di>
    <dd class="detail__device-version--version"><?php echo $deviceVersion->getVersion() ?></dd>
    <di class="detail__device-version--software-name__header">Software-Name</di>
    <dd class="detail__device-version--software-name"><?php echo $deviceVersion->getSoftwareName() ?></dd>
    <di class="detail__device-version--description__header">Beschreibung</di>
    <dd class="detail__device-version--description"><p><?php echo $deviceVersion->getDescription() ?></p></dd>
</dl>
<?php
	}
?>

<ul class="page-navigation">
	<li><form action="/admin/device/<?php echo $data['device']->getMac(); ?>/delete" method="post"><button type="submit">Löschen</button></form></li>
	<li><a href="/admin/device/<?php echo $data['device']->getMac(); ?>/edit">Ändern</a></li>
	<li><a href="/admin/device/<?php echo $data['device']->getMac(); ?>/version/new">Neue Version anlegen</a></li>
</ul>

<?php include('../templates/includes/html-foot.phtml'); ?>
