<?php include('../templates/includes/html-head.phtml'); ?>

<h1>ESP8266 für httpUpdate einrichten:</h1>

<?php
    # echo '<pre><code>';
    # var_dump($data);
    # echo '</code></pre>';
?><br>
<form action="" method="post" accept-charset="UTF-8" enctype="multipart/form-data" class="form form--upload">
<?php
    if (!empty($data['staMac'])) {
?>
    <input type="hidden" name="staMac" value="<?php echo $data['staMac']; ?>">
<?php
    }
?>
    <fieldset class="form__fieldset form__fieldset--type-text <?php echo !empty($data['msgs']['mac']) ? 'form__fieldset--error' : '' ?>">
        <label class="form__field__label" for="softwareName">MAC (STA-MAC):</label>
        <input class="form__field form__field--type-text" type="text" placeholder="14:14:14:14:14:14" value="<?php echo $data['device']->getMac() ?>" name="mac" id="mac">
        <p class="form__field__error-message"><?php echo $data['msgs']['mac'] ?></p>
    </fieldset>
    <fieldset class="form__fieldset form__fieldset--type-select <?php echo !empty($data['msgs']['type']) ? 'form__fieldset--error' : '' ?>">
        <label class="form__field__label" for="mac">Typ:</label>
        <select class="form__field form__field--type-select" name="type" id="type" >
            <option value="ESP-01" <?php echo $data['device']->getType() === 'ESP-01' ? 'selected' : '' ?>>ESP-01</option>
            <option value="ESP-201"<?php echo $data['device']->getType() === 'ESP-201' ? 'selected' : '' ?>>ESP-201</option>
            <option value="ESP-32"<?php echo $data['device']->getType() === 'ESP-32' ? 'selected' : '' ?>>ESP-32</option>
            <option value="ESP v3"<?php echo $data['device']->getType() === 'ESP v3' ? 'selected' : '' ?>>ESP v3</option>
        </select>
        <p class="form__field__error-message"><?php $data['msgs']['type'] ?></p>
    </fieldset>
    <fieldset class="form__fieldset form__fieldset--type-textarea <?php echo !empty($data['msgs']['deviceInfo']) ? 'form__fieldset--error' : '' ?>">
        <label class="form__field__label" for="deviceInfo">ESP-Name/Nummer, Standort:</label>
        <textarea class="form__field form__field--type-textarea" placeholder="Mehr Informationen zum ESP" name="deviceInfo" id="deviceInfo"><?php echo $data['device']->getInfo() ?></textarea>
        <p class="form__field__error-message"><?php echo $data['msgs']['deviceInfo'] ?></p>
    </fieldset>
    <fieldset class="form__fieldset form__fieldset--type-button">
        <button class="form__field form__field--type-button--submit" type="submit">Senden</button>
    </fieldset>
</form>

<?php include('../templates/includes/html-foot.phtml'); ?>
